# This is a basic workflow to help you get started with Actions

name: Hello-World
env:
  EB_PACKAGE_S3_BUCKET_NAME: "bucket-flask-hello-world"
  EB_APP_NAME: "flask-hello-world"
  EB_ENVIRONMENT_NAME: "Flaskhelloworld-env"
  DEPLOY_PACKAGE_NAME: "flask_hello_world_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_world_task:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Hello-World_print_here
        run: python3 main.py
  
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone my repository
        uses: actions/checkout@v2
        
      - name: Create ZIP 
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
             aws-region: ${{ env.AWS_REGION_NAME }}


      - name: Copy our Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/

 
      - name: Print message finish ci part
        run : echo "CI finished successfully"
  
  cd_part:
    runs-on: ubuntu-latest
    needs: [ci_part]
       
    steps:
      - name: Configure AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
             aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new ElasticBeanstalk Applicaiton Version
        run : |
            aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APP_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
            --version-label "V-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"
     
      - name: Deploy our Application Version
        run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "V-${{ github.sha }}"

      - name: Print message finish cd part
        run : echo "CD part finished successfully"
           
